### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by ghost** [madcodemonkey/ClassToDataTable#1]
Hey, 

I'd like to use this package in .NET Core v2.1. The following warning occurs: 

Package` 'ClassToDataTable 1.0.0.7' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

Could this package be ported to .NET Core 2.1?

Thx

**Comment by madcodemonkey** [comment]
I will most likely make this available in .NET Core 2.1 later this year (we have a new product that may use it).  As long as you are running this on Windows, you shouldn't have any compatible issues with it.  Let me know if you do run into any.

**Comment by madcodemonkey** [comment]
Converted to .NET Standard 2.0 for widest compatibility with both .NET Framework and .NET Core.
